'use client';

import React from 'react';
import ContactForm from "@/components/contactusForm";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-gray-800">
      {/* Page Header */}
      <section className="bg-green-900 text-white py-12">
        <div className="max-w-5xl mx-auto px-6">
          <h1 className="text-3xl md:text-5xl font-bold">Terms &amp; Conditions</h1>
          <p className="mt-2 text-lg opacity-90">
            Please read these Terms of Service carefully before using our platform.
          </p>
        </div>
      </section>

      {/* Terms Content */}
      <section className="max-w-5xl mx-auto px-6 py-10 leading-relaxed text-justify space-y-6">
        <p>
          This document is an electronic record in terms of the Information Technology Act,
          2000 and rules there under as applicable and the amended provisions pertaining to
          electronic records in various statutes as amended by the Information Technology Act,
          2000. This electronic record is generated by a computer system and does not require
          any physical or digital signatures.
        </p>

        <p>
          This document is published in accordance with the provisions of Rule 3 (1) of the
          Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing
          the rules and regulations, Privacy Policy, and Terms of Service for access or usage of
          domain name (
          <a href="https://www.regreenagro.in" className="text-green-900 underline">
            https://www.regreenagro.in
          </a>
          ).
        </p>

        <p>
          These Terms of Service (the &quot;Terms&quot;) constitute a legally binding agreement
          between Regreen Agro (&quot;Company&quot; or &quot;us&quot; or &quot;we&quot; or
          &quot;our&quot;), and you (&quot;user&quot; or &quot;you&quot; or &quot;your&quot;).
        </p>

        {/* ============================= */}
        {/* Sections Start */}
        {/* ============================= */}

        <h2 className="text-2xl font-semibold text-green-900 mt-10">USER ELIGIBILITY</h2>
        <p>
          Our Services are directed to be used by adults who are eighteen (18) years of age and
          above, and who can form legal contracts under applicable laws. If you are a minor,
          you may use the Platform only with the consent of a parent or legal guardian.
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">
          ACCESS TO OUR PLATFORM AND SERVICES
        </h2>
        <h3 className="text-xl font-semibold mt-4">Account Registration</h3>
        <p>
          To utilize the Service, you must register with us by setting up a user account (the
          &quot;Account&quot;). You must furnish accurate and complete details at the time of
          sign-up.
        </p>

        <h3 className="text-xl font-semibold mt-4">Account Security</h3>
        <ul className="list-disc ml-6 space-y-2">
          <li>You are responsible for safeguarding your account credentials.</li>
          <li>Any unauthorized use must be reported immediately.</li>
          <li>
            Sharing your account with others makes you fully liable for all activities
            performed under your account.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">CONTENT GUIDELINES</h2>
        <p>
          By uploading or posting content on our platform, you grant us a worldwide,
          royalty-free license to use such content in connection with our Services.
        </p>
        <ul className="list-disc ml-6 space-y-2">
          <li>
            Content must not contain defamatory, obscene, hateful, or unlawful material.
          </li>
          <li>
            Content must not promote illegal activity or infringe intellectual property rights.
          </li>
          <li>
            Content must not impersonate others or misrepresent your identity.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">
          ORDER, SALE, AND FULFILLMENT
        </h2>
        <p>
          When you place an order on our Platform, it constitutes a confirmed purchase. Vendors
          are solely responsible for fulfillment of orders.
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">PAYMENT TERMS</h2>
        <p>
          Users are authorized to use valid credit/debit cards, or other accepted payment
          methods for transactions. Payments are processed securely via Razorpay, Easebuzz, and
          other providers.
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">
          RETURNS, REFUNDS, AND CANCELLATION
        </h2>
        <p>
          All returns, refunds, and cancellations are governed by our Return and Cancellation
          Policy. For help, email{' '}
          <a href="mailto:regreenagro.marketing@gmail.com" className="text-green-900 underline">
            regreenagro.marketing@gmail.com
          </a>
          .
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">
          INTELLECTUAL PROPERTY RIGHTS
        </h2>
        <p>
          All intellectual property rights related to the Platform remain the property of
          Regreen Agro. You are granted only a limited, non-transferable license to use the
          Platform.
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">
          ACCEPTABLE USE POLICY
        </h2>
        <ul className="list-disc ml-6 space-y-2">
          <li>You must not use the Platform for unlawful purposes.</li>
          <li>
            You must not upload viruses, malicious software, or attempt to hack our systems.
          </li>
          <li>You must not use the Platform for spam, harassment, or abusive behavior.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">WARRANTIES</h2>
        <p>
          The Platform and Services are provided on an &quot;as-is&quot; basis without
          warranties of any kind. We disclaim all liability arising from use of the Services.
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">
          LIMITATION OF LIABILITY
        </h2>
        <p>
          To the fullest extent permitted by law, Regreen Agro shall not be liable for any
          indirect, incidental, special, or consequential damages arising out of your use of
          the Platform.
        </p>

        <h2 className="text-2xl font-semibold text-green-900 mt-10">CONTACT US</h2>
        <p>If you have any inquiries regarding these Terms of Service, please contact us at:</p>
        <p>
          📧 Email:{' '}
          <a href="mailto:regreenagro.marketing@gmail.com" className="text-green-900 underline">
            regreenagro.marketing@gmail.com
          </a>
        </p>
      </section>
      <section id="contact">
        <ContactForm />
        </section>
    </main>
  );
}
